# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transcription_service_pb2 as transcription__service__pb2


class TranscriptionServiceStub(object):
    """The transcription service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTranscription = channel.stream_stream(
                '/transcription.TranscriptionService/StreamTranscription',
                request_serializer=transcription__service__pb2.AudioChunk.SerializeToString,
                response_deserializer=transcription__service__pb2.TranscriptionResult.FromString,
                )
        self.FetchAIPredictions = channel.unary_unary(
                '/transcription.TranscriptionService/FetchAIPredictions',
                request_serializer=transcription__service__pb2.ConversationRequest.SerializeToString,
                response_deserializer=transcription__service__pb2.AIPredictionsResponse.FromString,
                )


class TranscriptionServiceServicer(object):
    """The transcription service definition.
    """

    def StreamTranscription(self, request_iterator, context):
        """Streams audio for transcription.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchAIPredictions(self, request, context):
        """Fetches AI predictions based on conversation ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscriptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTranscription': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTranscription,
                    request_deserializer=transcription__service__pb2.AudioChunk.FromString,
                    response_serializer=transcription__service__pb2.TranscriptionResult.SerializeToString,
            ),
            'FetchAIPredictions': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchAIPredictions,
                    request_deserializer=transcription__service__pb2.ConversationRequest.FromString,
                    response_serializer=transcription__service__pb2.AIPredictionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transcription.TranscriptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TranscriptionService(object):
    """The transcription service definition.
    """

    @staticmethod
    def StreamTranscription(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/transcription.TranscriptionService/StreamTranscription',
            transcription__service__pb2.AudioChunk.SerializeToString,
            transcription__service__pb2.TranscriptionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchAIPredictions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transcription.TranscriptionService/FetchAIPredictions',
            transcription__service__pb2.ConversationRequest.SerializeToString,
            transcription__service__pb2.AIPredictionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
